[colors.bright]
black = "#444444"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#5555dd"
cyan = "#55dddd"
green = "#55dd55"
magenta = "#dd55dd"
red = "#dd5555"
white = "#dddddd"
yellow = "#dddd55"

[colors.primary]
background = "#222222"
foreground = "#bbbbbb"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10.0

[font.normal]
family = "Source Code Pro"

[window]
dynamic_title = true
