[ui]
pager = "mpager"

[user]
name = "Allen Li"
email = "darkfeline@feleatra.moe"

[aliases]
d = ["diff"]
dno = ["diff", "--name-only"]
ds = ["describe"]
g = ["git"]
lh = ["log", "-r", "fork_point(heads(all()))::"]
n = ["new"]
sq = ["squash"]
