[ui]
pager = "mpager"

[user]
name = "Allen Li"
email = "darkfeline@feleatra.moe"

[revsets]
log = "present(@) | ancestors(immutable_heads().., 2) | trunk()"

[aliases]
d = ["diff"]
dno = ["diff", "--name-only"]
ds = ["describe"]
g = ["git"]
lm = ["log", "-r", "present(master):: | present(main)::"]
n = ["new"]
sq = ["squash"]
