[ui]
pager = "mpager"

[user]
name = "Allen Li"
email = "darkfeline@feleatra.moe"

[revsets]
log = "present(@) | ancestors(immutable_heads().., 2) | trunk()"

[aliases]
bm = ["bookmark", "move"]
d = ["diff"]
dno = ["diff", "--name-only"]
ds = ["describe"]
el = ["evolog"]
fu = ["file", "untrack"]
g = ["git"]
ge = ["git", "export"]
gf = ["git", "fetch"]
gi = ["git", "init"]
gp = ["git", "push"]
gr = ["git", "remote"]
lh = ["log", "-r", "fork_point(visible_heads())::visible_heads()"]
lm = ["log", "-r", "present(master):: | present(main)::"]
n = ["new"]
rb = ["rebase"]
sh = ["squash"]
